### FastAPI 서버 기본 테스트
GET http://localhost:8000/

### MCP Server Tool list
GET http://localhost:8000/tools

### Github Webhook
### https://smee.io/JsEoOmxPUGyv3cl 에 들어가서 Redeliver this payload

### Webhook 수신 테스트
POST http://localhost:8000/webhook
Content-Type: application/json
X-GitHub-Event: push

{
  "repository": {
    "full_name": "sjKang01401/webhook-test"
  },
  "head_commit": {
    "id": "66ba01b050bbc93d4d98b972ccdd7c1eaa282606"
  }
}

### SFR-099 테스트
POST http://localhost:8000/webhook
Content-Type: application/json
X-GitHub-Event: push

{
  "repository": {
    "full_name": "HorangApple/sports-portal"
  },
  "head_commit": {
    "id": "beff35bf72321a4e8cd9aaf4e4b068425ed4e798"
  }
}

### Pull Request Payload
POST http://localhost:8000/webhook
Content-Type: application/json
X-GitHub-Event: pull_request

{
  "pr_comment_send" : true,
  "number": 2,
  "pull_request": {
    "head": {
      "sha": "beff35bf72321a4e8cd9aaf4e4b068425ed4e798"
    }
  },
  "repository": {
    "full_name": "HorangApple/sports-portal"
  }
}