### FastAPI 서버 기본 테스트
GET http://localhost:8000/

### Github Webhook
### https://smee.io/JsEoOmxPUGyv3cl 에 들어가서 Redeliver this payload

### TEST (PR #5) : [SFR-113] 파일 9개 변경점
POST http://localhost:8000/webhook
Content-Type: application/json
X-GitHub-Event: pull_request

{
  "pr_comment_send" : true,
  "pr_comment_debug" : true,
  "number": 5,
  "pull_request": {
    "head": {
      "sha": "445f69cbadab6d6cdd0b9841cb3707e30fc66ff0",
      "ref": "SFR-113"
    }
  },
  "repository": {
    "full_name": "HorangApple/sports-portal"
  }
}

### TEST (PR #10) : [SFR-099] TestController.java 파일 1개 변경점
POST http://localhost:8000/webhook
Content-Type: application/json
X-GitHub-Event: pull_request

{
  "pr_comment_send" : true,
  "pr_comment_debug" : true,
  "number": 10,
  "pull_request": {
    "head": {
      "sha": "907ffad0242ed8e11e46b4e7cf353f259932c498",
      "ref": "SFR-099"
    }
  },
  "repository": {
    "full_name": "HorangApple/sports-portal"
  }
}